import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Share2, Copy, MessageSquare } from "lucide-react";
import { ALERTS, RISK_COLOR, RISK_BG, RISK_TEXT_CLASS, type RiskLevel } from "../mockData";

const RISK_EMOJI = { HIGH: "🔴", MEDIUM: "🟠", LOW: "🟢" };

type FilterTab = "All" | "High" | "Medium" | "Low";
const FILTERS: FilterTab[] = ["All", "High", "Medium", "Low"];

type Alert = typeof ALERTS[number];

// ─── Alert Detail Slide-over ──────────────────────────────────────────────────
function AlertDetail({ alert, onClose }: { alert: Alert; onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-50 flex justify-end">
      {/* Backdrop */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={onClose}
        className="absolute inset-0 bg-black/30 backdrop-blur-sm"
      />
      {/* Panel */}
      <motion.div
        initial={{ x: 480 }}
        animate={{ x: 0 }}
        exit={{ x: 480 }}
        transition={{ type: "spring", stiffness: 300, damping: 30 }}
        className="relative w-full max-w-[480px] bg-white shadow-2xl overflow-y-auto"
      >
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-100">
          <div>
            <h2 className="font-display text-xl font-bold text-[#0D1F1A]">{alert.location} Alert</h2>
            <p className="text-xs text-gray-400 font-mono">{alert.id}</p>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl hover:bg-gray-100 text-gray-400 hover:text-gray-600 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Risk banner */}
        <div
          className="px-6 py-4"
          style={{ background: RISK_BG[alert.risk], borderBottom: `3px solid ${RISK_COLOR[alert.risk]}` }}
        >
          <p className="text-sm font-bold" style={{ color: RISK_COLOR[alert.risk] }}>
            {RISK_EMOJI[alert.risk]} {alert.risk} RISK — {alert.pincode}
          </p>
          <p className="text-xs text-gray-600 mt-0.5">Alert issued by: Sanjeevani AI System · Mar 9, 2026 06:42</p>
        </div>

        <div className="p-6 space-y-5">
          {/* Info cards */}
          <div className="grid grid-cols-2 gap-3">
            {[
              { label: "Risk Level", value: alert.risk, color: RISK_COLOR[alert.risk] },
              { label: "Affected Area", value: alert.location },
              { label: "Generated By", value: "Sanjeevani AI" },
              { label: "Issued At", value: alert.time },
            ].map((info, i) => (
              <div key={i} className="bg-gray-50 rounded-xl p-3">
                <p className="text-[10px] text-gray-400 uppercase tracking-wider mb-0.5">{info.label}</p>
                <p className="text-sm font-semibold text-[#0D1F1A]" style={info.color ? { color: info.color } : {}}>
                  {info.value}
                </p>
              </div>
            ))}
          </div>

          {/* Description */}
          <div>
            <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Description</h4>
            <p className="text-sm text-gray-600 leading-relaxed">{alert.desc}</p>
          </div>

          {/* Sensor readings */}
          <div className="bg-gray-50 rounded-xl p-4 font-mono text-xs space-y-1.5">
            <div className="flex justify-between"><span className="text-gray-500">TDS</span><span className="font-bold text-[#0D1F1A]">{alert.tds} ppm</span></div>
            <div className="flex justify-between"><span className="text-gray-500">pH</span><span className="font-bold text-[#0D1F1A]">{alert.ph}</span></div>
            <div className="flex justify-between"><span className="text-gray-500">Turbidity</span><span className="font-bold text-[#0D1F1A]">{alert.turbidity}</span></div>
          </div>

          {/* Actionable steps */}
          <div>
            <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-3">Actionable Steps</h4>
            <ol className="space-y-2">
              {[
                "Boil all drinking water for minimum 10 minutes",
                "Avoid consuming raw foods washed with tap water",
                "Use ORS if experiencing diarrhea or vomiting",
                "Report symptoms to nearest ASHA worker",
                "Visit PHC Dispur if symptoms persist beyond 24 hours",
              ].map((step, i) => (
                <li key={i} className="flex items-start gap-2.5 text-sm text-gray-700">
                  <span className="w-5 h-5 rounded-full bg-[#0D1F1A] text-white text-[10px] font-bold flex items-center justify-center shrink-0 mt-0.5">
                    {i + 1}
                  </span>
                  {step}
                </li>
              ))}
            </ol>
          </div>

          {/* Share buttons */}
          <div>
            <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-3">Share this Alert</h4>
            <div className="flex gap-2">
              <button className="flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl bg-green-500 text-white text-xs font-semibold hover:bg-green-600 transition-colors">
                <Share2 className="w-3.5 h-3.5" /> WhatsApp
              </button>
              <button className="flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl border border-gray-200 text-gray-600 text-xs font-semibold hover:border-gray-300 transition-colors">
                <Copy className="w-3.5 h-3.5" /> Copy Link
              </button>
              <button className="flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl border border-gray-200 text-gray-600 text-xs font-semibold hover:border-gray-300 transition-colors">
                <MessageSquare className="w-3.5 h-3.5" /> SMS
              </button>
            </div>
          </div>

          {/* Related cases */}
          <div className="bg-[#FFF7ED] rounded-xl p-4 border border-orange-100">
            <p className="text-sm font-semibold text-[#0D1F1A]">🦠 {alert.cases} cases linked to this alert</p>
            <p className="text-xs text-gray-500 mt-0.5">Data from community reports and PHC registrations</p>
          </div>
        </div>
      </motion.div>
    </div>
  );
}

// ─── Alerts Section ──────────────────────────────────────────────────────────
export default function AlertsSection() {
  const [filter, setFilter] = useState<FilterTab>("All");
  const [selectedAlert, setSelectedAlert] = useState<Alert | null>(null);

  const filtered = ALERTS.filter((a) =>
    filter === "All" ? true : a.risk === filter.toUpperCase()
  );

  return (
    <>
      <div className="space-y-6">
        {/* Page header */}
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div>
            <h2 className="font-display text-[28px] font-bold text-[#0D1F1A]">Active Alerts</h2>
            <p className="text-sm text-gray-500 mt-0.5">Guwahati District · Updated 6 min ago</p>
          </div>
          {/* Filter pills */}
          <div className="flex gap-2 flex-wrap">
            {FILTERS.map((f) => (
              <button
                key={f}
                onClick={() => setFilter(f)}
                className={`px-4 py-1.5 rounded-full text-xs font-semibold border transition-all ${
                  filter === f
                    ? "bg-[#0D1F1A] text-white border-[#0D1F1A]"
                    : "bg-white text-gray-500 border-gray-200 hover:border-gray-300"
                }`}
              >
                {f === "High" ? "🔴" : f === "Medium" ? "🟠" : f === "Low" ? "🟢" : ""} {f}
              </button>
            ))}
          </div>
        </div>

        {/* Personal alert banner */}
        <div className="bg-[#FFF7ED] rounded-2xl border border-orange-100 p-5 flex items-center gap-5">
          <div className="text-3xl">⚠️</div>
          <div className="flex-1">
            <p className="font-semibold text-[#0D1F1A] text-sm">Your Area (781001) — <span className="text-[#FB8C00]">MEDIUM RISK</span></p>
            <p className="text-xs text-gray-500 mt-0.5">Alert issued by: Sanjeevani AI System · Mar 9, 2026 06:42 · Based on 14 cases + TDS 842 ppm</p>
          </div>
          <span className="text-[11px] font-bold px-3 py-1 rounded-full bg-[#FFF3E0] text-[#FB8C00] border border-orange-200">MEDIUM</span>
        </div>

        {/* Alerts grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
          {filtered.map((alert) => (
            <motion.div
              key={alert.id}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition-shadow"
            >
              {/* Top colored bar */}
              <div className="h-1" style={{ background: RISK_COLOR[alert.risk] }} />

              <div className="p-5">
                {/* Header */}
                <div className="flex items-start justify-between mb-2">
                  <div>
                    <h3 className="font-display font-bold text-[#0D1F1A] text-base leading-tight">{alert.location}</h3>
                    <span className="text-xs font-mono text-gray-400">{alert.pincode}</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    {alert.risk === "HIGH" && (
                      <span className="w-2 h-2 rounded-full animate-ping-ring" style={{ background: RISK_COLOR[alert.risk] }} />
                    )}
                    <span
                      className="text-[10px] font-bold px-2 py-0.5 rounded-full"
                      style={{ color: RISK_COLOR[alert.risk], background: RISK_BG[alert.risk] }}
                    >
                      {alert.risk}
                    </span>
                  </div>
                </div>

                <div className="h-px bg-gray-100 my-3" />

                {/* Cause */}
                <p className="text-sm text-gray-700 flex items-center gap-1.5 mb-2">
                  <span>{alert.causeIcon}</span>
                  <span className="font-medium">{alert.cause}</span>
                </p>

                {/* Sensor row */}
                <p className="text-[11px] font-mono text-gray-400">
                  TDS: {alert.tds} · pH: {alert.ph} · Turbidity: {alert.turbidity}
                </p>

                <div className="h-px bg-gray-100 my-3" />

                {/* Footer */}
                <div className="flex items-center justify-between">
                  <span className="text-[11px] text-gray-400">🕐 {alert.time}</span>
                  <button
                    onClick={() => setSelectedAlert(alert)}
                    className="text-xs font-semibold text-[#2ED8A3] hover:text-[#0D7A4A] transition-colors"
                  >
                    View Details →
                  </button>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Alert Detail Slide-over */}
      <AnimatePresence>
        {selectedAlert && <AlertDetail alert={selectedAlert} onClose={() => setSelectedAlert(null)} />}
      </AnimatePresence>
    </>
  );
}
